/* eslint-disable */

/**
 * Generated by Verge3D Puzzles v.4.12.0
 * Thu, 21 May 2026 02:28:38 GMT
 * Prefer not editing this file as your changes may get overridden once Puzzles are saved.
 * Check out https://www.soft8soft.com/docs/manual/en/introduction/Using-JavaScript.html
 * for the information on how to add your own JavaScript to Verge3D apps.
 */
function createPL(v3d = window.v3d) {

// global variables used in the init tab
const _initGlob = {
    percentage: 0,
    output: {
        initOptions: {
            fadeAnnotations: true,
            useBkgTransp: false,
            preserveDrawBuf: false,
            useCompAssets: false,
            useFullscreen: true,
            useCustomPreloader: false,
            preloaderStartCb: function() {},
            preloaderProgressCb: function() {},
            preloaderEndCb: function() {},
        },
    },
};


// global variables/constants used by puzzles' functions
var _pGlob = {};

_pGlob.objCache = new Map();
_pGlob.fadeAnnotations = true;
_pGlob.pickedObject = '';
_pGlob.hoveredObject = '';
_pGlob.mediaElements = {};
_pGlob.loadedFile = '';
_pGlob.states = [];
_pGlob.percentage = 0;
_pGlob.openedFile = '';
_pGlob.openedFileMeta = {};
_pGlob.xrSessionAcquired = false;
_pGlob.xrSessionCallbacks = [];
_pGlob.screenCoords = new v3d.Vector2();
_pGlob.intervalTimers = {};
_pGlob.customEvents = new v3d.EventDispatcher();
_pGlob.eventListeners = [];
_pGlob.htmlElements = new Set();
_pGlob.materialsCache = new Map();
_pGlob.css3Objects = new WeakMap();

_pGlob.AXIS_X = new v3d.Vector3(1, 0, 0);
_pGlob.AXIS_Y = new v3d.Vector3(0, 1, 0);
_pGlob.AXIS_Z = new v3d.Vector3(0, 0, 1);
_pGlob.MIN_DRAG_SCALE = 10e-4;
_pGlob.SET_OBJ_ROT_EPS = 1e-8;

_pGlob.vec2Tmp = new v3d.Vector2();
_pGlob.vec2Tmp2 = new v3d.Vector2();
_pGlob.vec3Tmp = new v3d.Vector3();
_pGlob.vec3Tmp2 = new v3d.Vector3();
_pGlob.vec3Tmp3 = new v3d.Vector3();
_pGlob.vec3Tmp4 = new v3d.Vector3();
_pGlob.eulerTmp = new v3d.Euler();
_pGlob.eulerTmp2 = new v3d.Euler();
_pGlob.quatTmp = new v3d.Quaternion();
_pGlob.quatTmp2 = new v3d.Quaternion();
_pGlob.colorTmp = new v3d.Color();
_pGlob.mat4Tmp = new v3d.Matrix4();
_pGlob.planeTmp = new v3d.Plane();
_pGlob.raycasterTmp = new v3d.Raycaster(); // always check visibility

const createPzLib = ({ v3d=null, appInstance=null }) => {
    function isObjectWorthProcessing(obj) {
        return obj.name !== '' &&
                !(obj.isMesh && obj.isMaterialGeneratedMesh) &&
                !obj.isAuxClippingMesh;
    }
        
    function getObjectByName(objName) {
        let objFound = null;
    
        // COMPAT: <4.9.0, old engine, new puzzles
        const isID = v3d.MathUtils.checkUUID ? v3d.MathUtils.checkUUID(objName) : false;
    
        const pGlobAvailable = _pGlob !== undefined;
        if (pGlobAvailable)
            objFound = _pGlob.objCache.get(objName);
    
        if (objFound && (isID ? objFound.uuid === objName : objFound.name === objName))
            return objFound;
    
        function findValidByName(obj, objName) {
            if ((isID ? obj.uuid === objName : obj.name === objName) && isObjectWorthProcessing(obj))
                return obj;
    
            for (let i = 0; i < obj.children.length; i++) {
                const child = obj.children[i];
                const object = findValidByName(child, objName);
                if (object !== null)
                    return object;
            }
    
            return null;
        }
    
        if (appInstance.scene) {
            objFound = findValidByName(appInstance.scene, objName);
            if (objFound && pGlobAvailable)
                _pGlob.objCache.set(objName, objFound);
        }
    
        return objFound;
    }
        
    function getObjectNamesByGroupName(groupName) {
        const objNameList = [];
        appInstance.scene.traverse(obj => {
            if (isObjectWorthProcessing(obj)) {
                const objGroupNames = obj.groupNames;
                if (!objGroupNames) {
                    return;
                }
    
                for (let i = 0; i < objGroupNames.length; i++) {
                    const objGroupName = objGroupNames[i];
                    if (objGroupName === groupName) {
                        objNameList.push(obj.name);
                    }
                }
            }
        });
        return objNameList;
    }
        
    function getAllObjectNames() {
        const objNameList = [];
        appInstance.scene.traverse(obj => {
            if (isObjectWorthProcessing(obj)) {
                objNameList.push(obj.name);
            }
        });
        return objNameList;
    }
        
    function retrieveObjectNamesAccum(currObjNames, namesAccum) {
        if (typeof currObjNames === 'string') {
            namesAccum.push(currObjNames);
        } else if (Array.isArray(currObjNames) && currObjNames[0] === 'GROUP') {
            const newObjNames = getObjectNamesByGroupName(currObjNames[1]);
            for (let i = 0; i < newObjNames.length; i++) {
                namesAccum.push(newObjNames[i]);
            }
        } else if (Array.isArray(currObjNames) && currObjNames[0] === 'ALL_OBJECTS') {
            const newObjNames = getAllObjectNames();
            for (let i = 0; i < newObjNames.length; i++) {
                namesAccum.push(newObjNames[i]);
            }
        } else if (Array.isArray(currObjNames)) {
            for (let i = 0; i < currObjNames.length; i++) {
                retrieveObjectNamesAccum(currObjNames[i], namesAccum);
            }
        }
    }
        
    function retrieveObjectNames(objNames) {
        const accum = [];
        retrieveObjectNamesAccum(objNames, accum);
        return accum.filter(name => name !== '');
    }
        
    function areListenersSame(target0, type0, listener0, optionsOrUseCapture0,
            target1, type1, listener1, optionsOrUseCapture1) {
        const capture0 = Boolean(optionsOrUseCapture0 instanceof Object
                ? optionsOrUseCapture0.capture : optionsOrUseCapture0);
        const capture1 = Boolean(optionsOrUseCapture1 instanceof Object
                ? optionsOrUseCapture1.capture : optionsOrUseCapture1);
        return target0 === target1 && type0 === type1 && listener0 === listener1
                && capture0 === capture1;
    }
        
    function bindListener(target, type, listener, optionsOrUseCapture) {
        const alreadyExists = _pGlob.eventListeners.some(elem => {
            return areListenersSame(elem.target, elem.type, elem.listener,
                    elem.optionsOrUseCapture, target, type, listener,
                    optionsOrUseCapture);
        });
    
        if (!alreadyExists) {
            target.addEventListener(type, listener, optionsOrUseCapture);
            _pGlob.eventListeners.push({ target, type, listener,
                    optionsOrUseCapture });
        }
    }
        
    function getElement(id, isParent=false) {
        let elem;
        if (Array.isArray(id) && id[0] === 'CONTAINER') {
            if (appInstance !== null) {
                elem = appInstance.container;
            } else if (typeof _initGlob !== 'undefined') {
                // if we are on the initialization stage, we still can have access
                // to the container element
                const contId = _initGlob.container;
                elem = isParent ? parent.document.getElementById(contId)
                        : document.getElementById(contId);
            }
        } else if (Array.isArray(id) && id[0] === 'WINDOW') {
            elem = isParent ? parent : window;
        } else if (Array.isArray(id) && id[0] === 'DOCUMENT') {
            elem = isParent ? parent.document : document;
        } else if (Array.isArray(id) && id[0] === 'BODY') {
            elem = isParent ? parent.document.body : document.body;
        } else if (Array.isArray(id) && (id[0] === 'QUERYSELECTOR' || id[0] === 'QUERYSELECTORALL')) {
            elem = isParent ? parent.document.querySelector(id[1]) : document.querySelector(id[1]);
        } else {
            elem = isParent ? parent.document.getElementById(id) : document.getElementById(id);
        }
        return elem;
    }
        
    function getElements(ids, isParent=false) {
        const elems = [];
        if (Array.isArray(ids) && ids[0] !== 'CONTAINER' && ids[0] !== 'WINDOW' && ids[0] !== 'DOCUMENT'
                && ids[0] !== 'BODY' && ids[0] !== 'QUERYSELECTOR' && ids[0] !== 'QUERYSELECTORALL') {
            for (let i = 0; i < ids.length; i++) {
                elems.push(getElement(ids[i], isParent));
            }
        } else if (Array.isArray(ids) && ids[0] === 'QUERYSELECTORALL') {
            const queryElems = isParent ? parent.document.querySelectorAll(ids[1]) : document.querySelectorAll(ids[1])
            // convert to array
            for (let i = 0; i < queryElems.length; i++)
                elems.push(queryElems[i]);
        } else {
            elems.push(getElement(ids, isParent));
        }
        return elems;
    }
        
    function getSceneAnimFrameRate(scene) {
        if (scene && 'animFrameRate' in scene.userData) {
            return scene.userData.animFrameRate;
        }
        return 24;
    }
        
    function getSceneByAction(action) {
        const root = action.getRoot();
        let scene = root.type === 'Scene' ? root : null;
        root.traverseAncestors(ancObj => {
            if (ancObj.type === 'Scene') {
                scene = ancObj;
            }
        });
        return scene;
    }

    return {
        getObjectByName, retrieveObjectNames, bindListener, getElements,
        getSceneAnimFrameRate, getSceneByAction,
    };
};

var PL = {};



// backward compatibility
if (v3d[Symbol.toStringTag] !== 'Module') {
    v3d.PL = v3d.puzzles = PL;
}

PL.procedures = PL.procedures || {};

PL.loadedLibraries = PL.loadedLibraries || [];



PL.execInitPuzzles = function(options) {
    // always null, should not be available in "init" puzzles
    var appInstance = null;
    // app is more conventional than appInstance (used in exec script and app templates)
    var app = null;

    const PzLib = createPzLib({ v3d });

    // provide the container's id to puzzles that need access to the container
    _initGlob.container = options !== undefined && 'container' in options
            ? options.container : "";

    

    
    return _initGlob.output;
}

PL.init = function(appInstance, initOptions) {

// app is more conventional than appInstance (used in exec script and app templates)
var app = appInstance;

const PzLib = createPzLib({ v3d, appInstance });

initOptions = initOptions || {};

if ('fadeAnnotations' in initOptions) {
    _pGlob.fadeAnnotations = initOptions.fadeAnnotations;
}



// assignMaterial puzzle
function assignMat(objSelector, matName, matIndex) {
    const objNames = PzLib.retrieveObjectNames(objSelector);
    if (!matName)
        return;

    const isMaterialInScene = (mat) => v3d.SceneUtils.getMaterialsByName(appInstance, mat.name).some(iMat => iMat === mat);
    const materialsCache = _pGlob.materialsCache;
    const mat = materialsCache.get(matName) || v3d.SceneUtils.getMaterialByName(appInstance, matName);
    if (!mat)
        return;
    for (let i = 0; i < objNames.length; i++) {
        const objName = objNames[i];
        if (!objName)
            continue;
        const obj = PzLib.getObjectByName(objName);
        if (obj) {
            const objsM = obj.resolveMultiMaterial();

            let objM;
            if (Number.isInteger(matIndex)) {
                if (matIndex >= 1 && matIndex <= objsM.length) {
                    objM = objsM[matIndex-1];
                } else {
                    console.error('assign material puzzle: Invalid material index ' + matIndex);
                    continue;
                }
            } else {
                objM = objsM[0];
            }

            const oldMat = objM.material;
            if (!oldMat)
                continue; // pass silently

            objM.material = mat;

            if (!isMaterialInScene(oldMat)) {
                materialsCache.set(oldMat.name, oldMat);
            }
        }
    }

    if (materialsCache.has(mat.name) && isMaterialInScene(mat)) {
        materialsCache.delete(mat.name);
    }
}

// eventHTMLElem puzzle
function eventHTMLElem(eventType, ids, isParent, callback) {
    var elems = PzLib.getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem)
            continue;

        PzLib.bindListener(elem, eventType, callback);
    }
}

_pGlob.animMixerCallbacks = [];

const initAnimationMixer = function() {

    function onMixerFinished(e) {
        const cb = _pGlob.animMixerCallbacks;
        const found = [];
        for (let i = 0; i < cb.length; i++) {
            if (cb[i][0] == e.action) {
                cb[i][0] = null; // desactivate
                found.push(cb[i][1]);
            }
        }
        for (let i = 0; i < found.length; i++) {
            found[i]();
        }
    }

    return function initAnimationMixer() {
        if (appInstance.mixer && !appInstance.mixer.hasEventListener('finished', onMixerFinished)) {
            PzLib.bindListener(appInstance.mixer, 'finished', onMixerFinished);
        }
    };

}();

// animation puzzles
function operateAnimation(operation, animations, from, to, loop, speed, callback, rev) {
    if (!animations)
        return;
    // input can be either single obj or array of objects
    if (typeof animations == "string")
        animations = [animations];

    function processAnimation(animName) {
        const action = v3d.SceneUtils.getAnimationActionByName(appInstance, animName);
        if (!action)
            return;

        let scene, frameRate, timeScale, callbacks;

        switch (operation) {
        case 'PLAY':
            if (!action.isRunning()) {
                action.reset();

                if (loop == 'AUTO') {
                    // COMPAT: < 4.10, old engine, new puzzles (no autoParams)
                    if (action.autoParams) {
                        action.loop = action.autoParams.loop;
                        action.repetitions = action.autoParams.repetitions;
                    } else {
                        action.repetitions = Infinity;
                    }
                } else {
                    action.loop = v3d[loop];
                    action.repetitions = Infinity;
                }

                scene = PzLib.getSceneByAction(action);
                frameRate = PzLib.getSceneAnimFrameRate(scene);
                timeScale = Math.abs(parseFloat(speed));

                if (rev)
                    timeScale *= -1;

                action.timeScale = timeScale;
                action.timeStart = from !== null ? from/frameRate : 0;
                if (to !== null) {
                    action.getClip().duration = to/frameRate;
                } else {
                    action.getClip().resetDuration();
                }
                action.time = timeScale >= 0 ? action.timeStart : action.getClip().duration;

                action.paused = false;
                action.play();

                // push unique callbacks only
                callbacks = _pGlob.animMixerCallbacks;
                let found = false;
                for (let j = 0; j < callbacks.length; j++)
                    if (callbacks[j][0] == action && callbacks[j][1] == callback)
                        found = true;

                if (!found)
                    _pGlob.animMixerCallbacks.push([action, callback]);
            }
            break;
        case 'STOP':
            action.stop();

            // remove callbacks
            callbacks = _pGlob.animMixerCallbacks;
            for (let j = 0; j < callbacks.length; j++)
                if (callbacks[j][0] == action) {
                    callbacks.splice(j, 1);
                    j--;
                }

            break;
        case 'PAUSE':
            action.paused = true;
            break;
        case 'RESUME':
            action.paused = false;
            break;
        case 'SET_FRAME':
            scene = PzLib.getSceneByAction(action);
            frameRate = PzLib.getSceneAnimFrameRate(scene);
            action.time = from ? from/frameRate : 0;
            action.play();
            action.paused = true;
            break;
        case 'SET_SPEED':
            timeScale = parseFloat(speed);
            action.timeScale = rev ? -timeScale : timeScale;
            break;
        }
    }

    for (let i = 0; i < animations.length; i++) {
        const animName = animations[i];
        if (animName)
            processAnimation(animName);
    }

    initAnimationMixer();
}


eventHTMLElem('click', 'body1', false, function(event) {
    assignMat(['GROUP', 'body'], 'body1', undefined);
});

eventHTMLElem('click', 'bonnet1', false, function(event) {
    assignMat(['GROUP', 'bonnet'], 'bonnet1', undefined);
});

eventHTMLElem('click', 'body2', false, function(event) {
    assignMat(['GROUP', 'body'], 'body2', undefined);
});

eventHTMLElem('click', 'bonnet2', false, function(event) {
    assignMat(['GROUP', 'bonnet'], 'bonnet2', undefined);
});

eventHTMLElem('click', 'grill1', false, function(event) {
    assignMat(['GROUP', 'grill'], 'grill1', undefined);
});

eventHTMLElem('click', 'interior1', false, function(event) {
    assignMat(['GROUP', 'interior'], 'int1', undefined);
});

eventHTMLElem('click', 'fld', false, function(event) {
    operateAnimation('PLAY', 'rrghost_door_FL_rrghost_leatherblue_0', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'fd', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'fd.001', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'fd.008', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'fd.007', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'fd.006', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'fd.005', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'fd.004', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'fd.003', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'fd.002', null, null, 'LoopOnce', 1, function() {}, false);
});

eventHTMLElem('click', 'body3', false, function(event) {
    assignMat(['GROUP', 'body'], 'body3', undefined);
});

eventHTMLElem('click', 'bonnet3', false, function(event) {
    assignMat(['GROUP', 'bonnet'], 'bonnet3', undefined);
});

eventHTMLElem('click', 'interior2', false, function(event) {
    assignMat(['GROUP', 'interior'], 'int2', undefined);
});

eventHTMLElem('click', 'grill2', false, function(event) {
    assignMat(['GROUP', 'grill'], 'grill2', undefined);
});

eventHTMLElem('click', 'body5', false, function(event) {
    assignMat(['GROUP', 'body'], 'body5', undefined);
});

eventHTMLElem('click', 'interior6', false, function(event) {
    assignMat(['GROUP', 'interior'], 'int6', undefined);
});

eventHTMLElem('click', 'grill3', false, function(event) {
    assignMat(['GROUP', 'grill'], 'grill3', undefined);
});

eventHTMLElem('click', 'body4', false, function(event) {
    assignMat(['GROUP', 'body'], 'body4', undefined);
});

eventHTMLElem('click', 'bonnet4', false, function(event) {
    assignMat(['GROUP', 'bonnet'], 'bonnet4', undefined);
});

eventHTMLElem('click', 'interior3', false, function(event) {
    assignMat(['GROUP', 'interior'], 'int3', undefined);
});

eventHTMLElem('click', 'frd', false, function(event) {
    operateAnimation('PLAY', 'rrghost_door_FR_rrghost_leatherblue_0', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'rd.010', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'rd', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'rd.009', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'rd.007', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'rd.006', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'rd.001', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'rd.003', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'rd.002', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'rd.004', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'rd.005', null, null, 'LoopOnce', 1, function() {}, false);
});

eventHTMLElem('click', 'body7', false, function(event) {
    assignMat(['GROUP', 'body'], 'body7', undefined);
});

eventHTMLElem('click', 'brd', false, function(event) {
    operateAnimation('PLAY', 'br.001', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'br', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'br.002', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'br.003', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'br.004', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'br.006', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'br.005', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'br.007', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'br.008', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'rrghost_door_RR_rrghost_leatherblue_0', null, null, 'LoopOnce', 1, function() {}, false);
});

eventHTMLElem('click', 'bon', false, function(event) {
    operateAnimation('PLAY', 'bonnet', null, null, 'LoopOnce', 1, function() {}, false);
});

eventHTMLElem('click', 'interior4', false, function(event) {
    assignMat(['GROUP', 'interior'], 'int4', undefined);
});

eventHTMLElem('click', 'body6', false, function(event) {
    assignMat(['GROUP', 'body'], 'body6', undefined);
});

eventHTMLElem('click', 'bonnet6', false, function(event) {
    assignMat(['GROUP', 'bonnet'], 'bonnet6', undefined);
});

eventHTMLElem('click', 'interior5', false, function(event) {
    assignMat(['GROUP', 'interior'], 'int5', undefined);
});

eventHTMLElem('click', 'trk', false, function(event) {
    operateAnimation('PLAY', 'diggi', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'diggi.001', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'diggi.002', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'diggi.003', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'diggi.004', null, null, 'LoopOnce', 1, function() {}, false);
});

eventHTMLElem('click', 'bonnet8', false, function(event) {
    assignMat(['GROUP', 'bonnet'], 'bonnet8', undefined);
});

eventHTMLElem('click', 'body8', false, function(event) {
    assignMat(['GROUP', 'body'], 'body8', undefined);
});

eventHTMLElem('click', 'bonnet5', false, function(event) {
    assignMat(['GROUP', 'bonnet'], 'bonnet5', undefined);
});

eventHTMLElem('click', 'body9', false, function(event) {
    assignMat(['GROUP', 'body'], 'body9', undefined);
});

eventHTMLElem('click', 'bonnet9', false, function(event) {
    assignMat(['GROUP', 'bonnet'], 'bonnet9', undefined);
});

eventHTMLElem('click', 'bld', false, function(event) {
    operateAnimation('PLAY', 'bl.007', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'bl.006', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'bl.005', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'bl.004', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'bl.003', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'bl.002', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'bl.001', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'bl', null, null, 'LoopOnce', 1, function() {}, false);
    operateAnimation('PLAY', 'rrghost_door_RL_rrghost_leatherblue_0', null, null, 'LoopOnce', 1, function() {}, false);
});

eventHTMLElem('click', 'interior7', false, function(event) {
    assignMat(['GROUP', 'interior'], 'int7', undefined);
});

eventHTMLElem('click', 'body10', false, function(event) {
    assignMat(['GROUP', 'body'], 'body10', undefined);
});

eventHTMLElem('click', 'bonnet10', false, function(event) {
    assignMat(['GROUP', 'bonnet'], 'bonnet10', undefined);
});

eventHTMLElem('click', 'interior8', false, function(event) {
    assignMat(['GROUP', 'interior'], 'int8', undefined);
});

eventHTMLElem('click', 'bonnet7', false, function(event) {
    assignMat(['GROUP', 'bonnet'], 'bonnet7', undefined);
});



} // end of PL.init function

PL.disposeListeners = function() {
    if (_pGlob) {
        _pGlob.eventListeners.forEach(({ target, type, listener, optionsOrUseCapture }) => {
            target.removeEventListener(type, listener, optionsOrUseCapture);
        });
        _pGlob.eventListeners.length = 0;
    }
}

PL.disposeHTMLElements = function() {
    if (_pGlob) {
        _pGlob.htmlElements.forEach(elem => {
            elem.remove();
        });
        _pGlob.htmlElements.clear();
    }
}

PL.disposeMaterialsCache = function() {
    if (_pGlob) {
        for (const mat of _pGlob.materialsCache.values()) {
            mat.dispose();
        }
        _pGlob.materialsCache.clear();
    }
}

PL.dispose = function() {
    PL.disposeListeners();
    PL.disposeHTMLElements();
    PL.disposeMaterialsCache();
    _pGlob = null;
    // backward compatibility
    if (v3d[Symbol.toStringTag] !== 'Module') {
        delete v3d.PL;
        delete v3d.puzzles;
    }
}



return PL;

}

export { createPL };
